<div class="counsel_center">
<img class="btn_counsel" src="../common/images/coun_center.png" width="195" height="30" title="カウンセリングセンター" alt="カウンセリングセンター" />
<div class="contact_info">
<img class="contact_box" src="../common/images/contact_box.png" width="164" height="149" title="フリーダイヤル 0120-922-308　携帯電話から03-3986-3475 月～土10：00～21：00 日10：00～19：00(祝日は定休日となります)" alt="フリーダイヤル 0120-922-308　携帯電話から03-3986-3475 月～土10：00～21：00 日10：00～19：00(祝日は定休日となります)" />
<div class="counsel_name"><a href="../company/place.html#anchor01" title="池袋カウンセリングセンター">池袋カウンセリングセンター</a></div>
<a href="../company/place.html#anchor01" title="池袋カウンセリングセンター"><img class="counsel_img" src="../common/images/little_img01.jpg" width="162" height="37" title="池袋カウンセリングセンター" alt="池袋カウンセリングセンター" /></a>
<ul class="work_time">
<li class="first">池袋駅　徒歩3分</li>
<li>03-3986-3475（祝日：定休）</li>
<li>月-土/ 10：00 ～ 21：00</li>
<li class="last">　 日/ 10：00 ～ 19：00</li>
</ul>

<div class="counsel_name"><a href="../company/place.html#anchor02" title="松戸カウンセリングセンター">松戸カウンセリングセンター</a></div>
<a href="../company/place.html#anchor02" title="松戸カウンセリングセンター"><img class="counsel_img" src="../common/images/little_img02.jpg" width="162" height="37" title="松戸カウンセリングセンター" alt="松戸カウンセリングセンター" /></a>
<ul class="work_time">
<li class="first">松戸駅　徒歩5分</li>
<li>047-366-1879</li>
<li>（水日祝：定休）</li>
<li class="last">10：00 ～ 19：00</li>
</ul>

<div class="counsel_name"><a href="../company/place.html#anchor03" title="埼玉カウンセリングセンター">埼玉カウンセリングセンター</a></div>
<a href="../company/place.html#anchor03" title="埼玉カウンセリングセンター"><img class="counsel_img" src="../common/images/little_img03.jpg" width="162" height="37" title="埼玉カウンセリングセンター" alt="埼玉カウンセリングセンター" /></a>
<ul class="work_time">
<li class="first">大宮駅　バス5分</li>
<li>048-645-6994</li>
<li>（水日祝：定休）</li>
<li class="last">10：00 ～ 19：00</li>
</ul>

<div class="counsel_name"><a href="../company/place.html#anchor04" title="横浜カウンセリングセンター">横浜カウンセリングセンター</a></div>
<a href="../company/place.html#anchor04" title="横浜カウンセリングセンター"><img class="counsel_img" src="../common/images/little_img04.jpg" width="162" height="37" title="横浜カウンセリングセンター" alt="横浜カウンセリングセンター" /></a>
<ul class="work_time">
<li class="first">桜木町駅　徒歩3分</li>
<li>0120-922-308</li>
<li>（水日祝：定休）</li>
<li class="last">10：00 ～ 19：00</li>
</ul>

<div class="counsel_name"><a href="../company/place.html#anchor05" title="立川カウンセリングセンター">立川カウンセリングセンター</a></div>
<a href="../company/place.html#anchor05" title="立川カウンセリングセンター"><img class="counsel_img" src="../common/images/little_img05.jpg" width="162" height="37" title="立川カウンセリングセンター" alt="立川カウンセリングセンター" /></a>
<ul class="work_time">
<li class="first">立川駅　徒歩5分～7分</li>
<li>0120-922-307</li>
<li>（水日祝：定休）</li>
<li class="last">10：00 ～ 19：00</li>
</ul>

<div class="counsel_name">大阪カウンセリングセンター</div>
<img class="counsel_img" src="../common/images/little_img06.jpg" width="162" height="37" title="大阪カウンセリングセンター" alt="大阪カウンセリングセンター" />
<ul class="work_time">
<li class="first">京橋駅　徒歩10分</li>
<li>06-6351-1927（火水：営業）</li>
<li>14：00～18：00</li>
<li class="last">フレンドスペースにて</li>
</ul>
</div>
</div>