<div class="introduction01 float-left">
<div class="introduction02 float-left">
<div class="introduction03 float-left">
<img src="../common/images/btn_introduction03.png" width="680" height="34" alt="ご相談場所について" title="ご相談場所について" />
<ul class="intro_list blue">
<li><a href="../company/place.html#anchor01" title="池袋カウンセリングセンター">池袋カウンセリングセンター</a></li>
<li><a href="../company/place.html#anchor02" title="松戸カウンセリングセンター">松戸カウンセリングセンター</a></li>
<li><a href="../company/place.html#anchor03" title="埼玉カウンセリングセンター">埼玉カウンセリングセンター</a></li>
<li><a href="../company/place.html#anchor04" title="横浜カウンセリングセンター">横浜カウンセリングセンター</a></li>
<li><a href="../company/place.html#anchor05" title="立川カウンセリングセンター">立川カウンセリングセンター</a></li>
</ul>
<img src="../common/images/btn_relevant.png" width="680" height="29" alt="関連ページへ" title="関連ページへ" />
<ul class="relevant_list">
<li><a class="fade" href="../consultation/category.html" title="カウンセリングの種類・方法">カウンセリングの種類・方法</a></li>
<li><a class="fade" href="../consultation/way.html" title="どんな相談方法があるの？">どんな相談方法があるの？</a></li>
<li class="last"><a class="fade" href="../consultation/ethic.html" title="安心してカウンセリングを受けてもらうために">安心してカウンセリングを受けてもらうために</a></li>
</ul> 
</div>
</div>
</div>