<div class="introduction01 float-left">
<div class="introduction02 float-left">
<div class="introduction03 float-left">
<img src="../common/images/btn_introduction02.png" width="680" height="34" alt="その他のカウンセリングの種類・ご相談方法について" title="その他のカウンセリングの種類・ご相談方法について" />
<ul class="intro_list green">
<li><a class="fade" href="../consultation/category.html" title="カウンセリングの種類">カウンセリングの種類</a></li>
<li><a class="fade" href="../consultation/way.html" title="どんな相談方法があるの？">どんな相談方法があるの？</a></li>
<li><a class="fade" href="../consultation/voice.html" title="ご利用の皆様の声子">ご利用の皆様の声</a></li>
<li><a class="fade" href="../consultation/category.html#reserve" title="限定カウンセリング">限定カウンセリング</a></li>
<li><a class="fade" href="../consultation/ethic.html" title="安心してカウンセリングを受けてもらうために">安心してカウンセリングを受けてもらうために</a></li>
<li><a class="fade" href="../consultation/index.html" title="カウンセリングの種類・ご相談方法について一覧">カウンセリングの種類・ご相談方法について一覧</a></li>
</ul>
<img src="../common/images/btn_relevant.png" width="680" height="29" alt="関連ページへ" title="関連ページへ" />
<ul class="relevant_list">
<li><a class="fade" href="../consultation/category.html" title="カウンセリングの種類・方法">カウンセリングの種類・方法</a></li>
<li><a class="fade" href="../consultation/way.html" title="どんな相談方法があるの？">どんな相談方法があるの？</a></li>
<li class="last"><a class="fade" href="../consultation/ethic.html" title="安心してカウンセリングを受けてもらうために">安心してカウンセリングを受けてもらうために</a></li>
</ul> 
</div>
</div>
</div>