<div class="introduction01 float-left">
<div class="introduction02 float-left">
<div class="introduction03 float-left">
<img src="../common/images/btn_introduction.png" width="680" height="34" alt="その他カウンセラー紹介" title="その他カウンセラー紹介" />
<ul class="intro_list">
<li><a class="fade" href="../counselor/detail01.html" title="【箱庭療法】植村 和子">【箱庭療法】植村 和子</a></li>
<li><a class="fade" href="../counselor/detail02.html" title="【フォーカシング】淵上 規后子">【フォーカシング】淵上 規后子</a></li>
<li><a class="fade" href="../counselor/detail03.html" title="【不妊カウンセリング】赤城 惠子">【不妊カウンセリング】赤城 惠子</a></li>
<li><a class="fade" href="../counselor/detail04.html" title="【認知行動療法】玉井 仁">【認知行動療法】玉井 仁</a></li>
<li><a class="fade" href="../counselor/detail05.html" title="【ゲシュタルト】高畑 キヤ子">【ゲシュタルト】高畑 キヤ子</a></li>
<li><a class="fade" href="../counselor/list.html" title="その他カウンセラー一覧">その他カウンセラー一覧</a></li>
<li><a class="fade" href="../counselor/index.html" title="全てのカウセラー一覧">全てのカウセラー一覧</a></li>
</ul>
<img src="../common/images/btn_relevant.png" width="680" height="29" alt="関連ページへ" title="関連ページへ" />
<ul class="relevant_list">
<li><a class="fade" href="../consultation/category.html" title="カウンセリングの種類・方法">カウンセリングの種類・方法</a></li>
<li><a class="fade" href="../consultation/way.html" title="どんな相談方法があるの？">どんな相談方法があるの？</a></li>
<li class="last"><a class="fade" href="../consultation/ethic.html" title="安心してカウンセリングを受けてもらうために">安心してカウンセリングを受けてもらうために</a></li>
</ul> 
</div>
</div>
</div>