<div class="btn_contact">
<a class="float-left" href="mailto&#58;in&#102;&#111;&#64;&#109;&#101;&#110;&#116;&#97;&#108;&#104;&#101;alt&#104;.&#106;p" title="まずはお気軽にご連絡ください メールでのお問い合わせ"><img src="images/btn_contact01_off.png" width="348" height="80" title="まずはお気軽にご連絡ください メールでのお問い合わせ" alt="まずはお気軽にご連絡ください メールでのお問い合わせ" /></a>
<a class="float-right" href="https://www.tmaweb.net/cgi-bin/corder/cordernew.cgi" target="_blank" title="いつでもお待ちしています 各種ご相談お申し込み"><img src="images/btn_contact02_off.png" width="347" height="80" title="いつでもお待ちしています 各種ご相談お申し込み" alt="いつでもお待ちしています 各種ご相談お申し込み" /></a>
</div>