<div class="footer">
<div class="foot-left float-left">
<ul class="footer-ul01">
<li><a href="http://www.tmaweb.net/kojin/taimen/heartfulticket.html" target="_blank" title="ハートフルチケット 大切な人に元気でいてもらいたい"><img src="../common/images/footer-ul01-img01_off.png" width="197" height="73" title="ハートフルチケット 大切な人に元気でいてもらいたい" alt="ハートフルチケット 大切な人に元気でいてもらいたい" /></a></li>
<li><a href="http://www.tmaweb.net/kojin/scounseling/" target="_blank" title="回数限定チケット もっと身近で、分かりやすい相談に"><img src="../common/images/footer-ul01-img02_off.png" width="198" height="73" title="回数限定チケット もっと身近で、分かりやすい相談に" alt="回数限定チケット もっと身近で、分かりやすい相談に" /></a></li>
<li><a href="http://www.tmaweb.net/voicecounseling/" target="_blank" title="ヴォイスカウンセリング コミュニケーションに自信を持ちたい"><img src="../common/images/footer-ul01-img03_off.png" width="199" height="73" title="ヴォイスカウンセリング コミュニケーションに自信を持ちたい" alt="ヴォイスカウンセリング コミュニケーションに自信を持ちたい" /></a></li>
<li><a href="http://www.tmaweb.net/colortherapy/index.htm" target="_blank" title="カラーセラピー あなたの心の色をのぞいてみよう"><img src="../common/images/footer-ul01-img04_off.png" width="199" height="73" title="カラーセラピー あなたの心の色をのぞいてみよう" alt="カラーセラピー あなたの心の色をのぞいてみよう" /></a></li>
<li><a href="http://www.tmaweb.net/academy/index.php" target="_blank" title="東京メンタルヘルスアカデミー"><img src="../common/images/footer-ul01-img05_off.png" width="196" height="73" title="東京メンタルヘルスアカデミー" alt="東京メンタルヘルスアカデミー" /></a></li>
</ul>
<ul class="footer-ul02">
<li class="footer-ul02-dot02"><a class="fade" href="../concept/index.html" title="カウンセリングへの想い">カウンセリングへの想い</a></li>
<li class="footer-ul02-dot02 last"><a class="fade" href="../cause/index.html" title="こんなことに悩んでいませんか？">こんなことに<br />
悩んでいませんか？</a></li>
<li><a href="http://www.tmaweb.net/academy/index.php" target="_blank" title="講座・研修会">講座・研修会</a></li>
<li><a class="fade" href="../qa.html" title="よくあるご質問">よくあるご質問</a></li>
<li><a class="fade" href="../info.html" title="お知らせ・新着情報">お知らせ・新着情報</a></li>
<li><a href="mailto&#58;in&#102;&#111;&#64;&#109;&#101;&#110;&#116;&#97;&#108;&#104;&#101;alt&#104;.&#106;p" title="お問い合わせ">お問い合わせ</a></li>
<li><a href="https://www.tmaweb.net/cgi-bin/corder/cordernew.cgi" target="_blank" title="ご予約お申込み">ご予約お申込み</a></li>
<li><a href="https://www.tmaweb.net/kojin/html/croom.htm" target="_blank" title="会員様ログイン">会員様ログイン</a></li>
</ul>
<ul class="footer-ul02 footer-ul03">
<li class="footer-ul02-dot02 last"><a class="fade" href="../consultation/index.html" title="カウンセリングの種類・ご相談について">カウンセリングの<br />
種類・ご相談について</a></li>
<li><a class="fade" href="../consultation/about.html" title="そもそもカウンセリングって？">そもそもカウンセリングって？</a></li>
<li><a class="fade" href="../consultation/category.html" title="カウンセリングの種類・方法">カウンセリングの種類・方法</a></li>
<li><a class="fade" href="../consultation/way.html" title="どんな相談方法があるの？">どんな相談方法があるの？</a></li> 
<li><a class="fade" href="../consultation/voice.html" title="ご利用者の皆様の声">ご利用者の皆様の声</a></li> 
<li><a class="fade" href="../consultation/ethic.html" title="安心してカウンセリングを受けてもらうために">安心してカウンセリングを<br />
受けてもらうために</a></li>
</ul>
<ul class="footer-ul02 footer-ul04">
<li class="footer-ul02-dot02 last"><a class="fade" href="../counselor/index.html" title="カウンセラーのご紹介">カウンセラーのご紹介</a></li>
<li><a class="fade" href="../counselor/detail01.html" title="【箱庭療法】植村 和子">【箱庭療法】植村 和子</a></li>
<li><a class="fade" href="../counselor/detail02.html" title="【フォーカシング】淵上 規后子">【フォーカシング】淵上 規后子</a></li>
<li><a class="fade" href="../counselor/detail03.html" title="【不妊カウンセリング】赤城 惠子">【不妊カウンセリング】赤城 惠子</a></li>
<li><a class="fade" href="../counselor/detail04.html" title="【認知行動療法】玉井 仁">【認知行動療法】玉井 仁</a></li>
<li><a class="fade" href="../counselor/detail05.html" title="【ゲシュタルト】高畑 キヤ子">【ゲシュタルト】高畑 キヤ子</a></li>
<li><a class="fade" href="../counselor/list.html" title="その他カウンセラー一覧">その他カウンセラー一覧</a></li> 
</ul>
<ul class="footer-ul02 footer-ul05">
<li class="footer-ul02-dot02 last"><a class="fade" href="../company/index.html" title="カウンセリングセンター">カウンセリングセンター</a></li>
<li><a href="../company/outline.html#anchor02" title="会社概要・沿革">会社概要・沿革</a></li>
<li><a href="../company/outline.html#anchor01" title="ご挨拶">ご挨拶</a></li>
<li><a class="fade" href="../company/place.html" title="ご相談場所について（センターのご案内）">ご相談場所について<br />
（センターのご案内）</a></li> 
<li class="back-none">
<a href="../company/place.html#anchor01" class="float-left" title="池袋"><img src="../common/images/foot-ul05-img01.png" width="48" height="18" title="池袋" alt="池袋" /></a>
<a href="../company/place.html#anchor04" class="float-right" title="横浜"><img src="../common/images/foot-ul05-img02.png" width="48" height="18" title="横浜" alt="横浜" /></a>
<a href="../company/place.html#anchor02" class="float-left" title="松戸"><img src="../common/images/foot-ul05-img03.png" width="48" height="18" title="松戸" alt="松戸" /></a>
<a href="../company/place.html#anchor05" class="float-right" title="立川"><img src="../common/images/foot-ul05-img04.png" width="48" height="18" title="立川" alt="立川" /></a>
<a href="../company/place.html#anchor03" class="float-left" title="埼玉"><img src="../common/images/foot-ul05-img05.png" width="48" height="18" title="埼玉" alt="埼玉" /></a>
</li>
</ul>
<div class="foot-div01 float-left">
<ul class="CMSlink clearfix">
<li><a href="http://www.facebook.com/TokyoMentalhealth" target="_blank"><img src="../common/images/facebook_bn_off.png" alt="facebook" title="facebook"></a></li>
<li><a href="http://twitter.com/TOKYO_MENTAL" target="_blank"><img src="../common/images/twitter_bn_off.png" alt="twitter" title="twitter"></a></li>
</ul>
<div class="foot-div02 float-left">
<p class="foot-p01">東京メンタルヘルス株式会社 <span>～ 心理カウンセリング・メンタルケア ～</span></p>
<p class="foot-p02">〒171-0021 東京都豊島区西池袋2-39-8 ローズベイ池袋ビル3階<br />
TEL：03-3986-3220　FAX：03-3986-3240</p>
<p class="foot-p03"><script type="text/javascript">
copyright();
</script></p>
</div>
<ul class="footer-ul06 float-right">
<li class="foot-ul06-li01"><a href="http://www.tmaweb.net/" target="_blank" title="東京メンタルヘルス コーポレートサイト">東京メンタルヘルス コーポレートサイト</a></li>
<li class="foot-ul06-li02"><a href="http://www.tmaweb.net/houjin/" target="_blank" title="法人のお客様向けサービス / EAP">法人のお客様向けサービス / EAP</a></li>
</ul>
</div>


</div>
<div class="foot-div03 float-right">
<div class="float-left"><img src="../common/images/ft-dv03-img01.png" width="181" height="32" title="まずはお気軽にご連絡ください" alt="まずはお気軽にご連絡ください" /></div>
<div class="ft-dv03-img02 float-left"><img src="../common/images/ft-dv03-img02.png" width="181" height="141" title="フリーダイヤル 0120-922-308　携帯電話から03-3986-3475 月～土10：00～21：00 日10：00～19：00(祝日は定休日となります)" alt="フリーダイヤル 0120-922-308　携帯電話から03-3986-3475 月～土10：00～21：00 日10：00～19：00(祝日は定休日となります)" /></div>
<a href="mailto&#58;in&#102;&#111;&#64;&#109;&#101;&#110;&#116;&#97;&#108;&#104;&#101;alt&#104;.&#106;p" class="float-left" title="メールでのお問い合わせ"><img src="../common/images/ft-dv03-img03_off.png" width="181" height="59" title="メールでのお問い合わせ" alt="メールでのお問い合わせ" /></a>
<p class="ft-dv03-p01 float-left">心の中に未解決なことは<br />
ありませんか？<br />
お1人で抱えていませんか？<br />
カウンセリングを受けることに<br />
ついてご不安はありませんか？
</p>

</div>
</div><!--end footer-->


<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30491821-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>