<ul class="category">
<li><a class="fade" href="../concept/index.html" title="カウンセリングへの想い ～あなたの気持ちをやわらげたいから"><img src="../common/images/category01_off.png" width="204" height="55" title="カウンセリングへの想い ～あなたの気持ちをやわらげたいから" alt="カウンセリングへの想い ～あなたの気持ちをやわらげたいから" /></a></li>
<li><a class="fade" href="../company/index.html" title="東京メンタルヘルスご相談場所 カウンセリングセンター"><img src="../common/images/category02_off.png" width="200" height="55" title="東京メンタルヘルスご相談場所 カウンセリングセンター" alt="東京メンタルヘルスご相談場所 カウンセリングセンター" /></a></li>
<li><a class="fade" href="../consultation/index.html" title="カウンセリングの種類・ご相談方法について"><img src="../common/images/category03_off.png" width="202" height="55" title="カウンセリングの種類・ご相談方法について" alt="カウンセリングの種類・ご相談方法について" /></a></li>
<li class="last"><a class="fade" href="../counselor/index.html" title="あなたの心の声を聴く カウンセラーの紹介"><img src="../common/images/category04_off.png" width="153" height="55" title="あなたの心の声を聴く カウンセラーの紹介" alt="あなたの心の声を聴く カウンセラーの紹介" /></a></li>
</ul>
<div class="person">
<img src="../common/images/person.png" width="110" height="144" title="カウンセラー" alt="カウンセラー" />
</div>