<img class="title-leftmenu" src="common/images/cnt-title_leftmenu.png" width="141" height="34" title="東京メンタルヘルス サービスメニュー" alt="東京メンタルヘルス サービスメニュ" />
<ul class="news_list">
<li><a class="fade" href="qa.html" title="よくあるご質問"><img src="common/images/link01_off.png" width="113" height="13" title="よくあるご質問" alt="よくあるご質問" /></a></li>
<li><a href="http://www.tmaweb.net/academy/index.php" target="_blank" title="講座・研修会情報"><img src="common/images/link02_off.png" width="134" height="12" title="講座・研修会情報" alt="講座・研修会情報" /></a></li>
<li><a class="fade" href="info.html" title="お知らせ"><img src="common/images/link03_off.png" width="76" height="13" title="お知らせ" alt="お知らせ" /></a></li>
<li><a href="mailto&#58;in&#102;&#111;&#64;&#109;&#101;&#110;&#116;&#97;&#108;&#104;&#101;alt&#104;.&#106;p" title="お問い合わせ"><img src="common/images/link04_off.png" width="108" height="12" title="お問い合わせ" alt="お問い合わせ" /></a></li>
<li><a href="https://www.tmaweb.net/cgi-bin/corder/cordernew.cgi" target="_blank" title="ご予約お申し込み"><img src="common/images/link05_off.png" width="123" height="12" title="ご予約お申し込み" alt="ご予約お申し込み" /></a></li>
<li class="last"><a href="https://www.tmaweb.net/kojin/html/croom.htm" target="_blank" title="会員ログイン"><img src="common/images/link06_off.png" width="101" height="12" title="会員ログイン" alt="会員ログイン" /></a></li>
</ul>